### ISSUE TITLE
Implement a continuous integration system

### ISSUE THREAD

**Issue by devimc** [clearcontainers/tests#132]
The continuous integration system should be able to

- [x] Monitor repositories
- [x] Monitor a specific repository
- [x] Trigger the tests when a specific comment is added in the pull request
- [x] Fetch the pull requests
- [x] Run the tests
- [x] Create comments in the pull request
- [x] Install a specific version of a language

**Comment by gorozco1** [comment]
- [x] Update versions file
- [x] Create OBS packages
