### ISSUE TITLE
Investigate how to run ciao-down under semaphoreCI 

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#144]
semaphoreCI runs under an old ubuntu version ( 14.04 ) and we have hit some issues because old dependency versions that are used for CC and cri-o. Because of that, we need to check if using ciao-down (or maybe something else in the future) with a newer version of ubuntu (or other distro) can help us being more reliable.

**Comment by sboeuf** [comment]
Thanks for opening this issue !

**Comment by chavafg** [comment]
This task is already done in #247
