### ISSUE TITLE
functional: ginkgo/gomega: use Expect not Ω

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/tests#192]
When using ginkgo (technically, the gomega pattern matcher with ginkgo) in our tests, can we stick to using the `Expect` API call, and not the `Ω` call.
`Ω` is just going to cause us issues later on searching, parsing, or some similar general confusion, and `Expect` is functionally identical and tbh 'says what it does on the tin' more for me.
http://onsi.github.io/gomega/#making-assertions

**Comment by devimc** [comment]
> Ω is just going to cause us issues later on searching, parsing, or some similar general confusion, and 

I don't think so, ```Ω``` and ```Expect``` are the same thing

**Comment by grahamwhaley** [comment]
It's obviously not going to cause technical run issues - as I said, they are functionally equivalent (as noted in the gomega docs). But, adding basically a non-ascii character into our codebase, particularly when it is not necessary, is horrid. Don't do it. Undo it.

**Comment by devimc** [comment]
ehmm nop, the use of non-ascii characters is one of the advantages that Go offers us and is not horrid if it was then why ginkgo implement it? why Go support this? - This is one of the cool features of Go.

**Comment by grahamwhaley** [comment]
If so @devimc, why did they also supply an ascii named fully equivalent function as well?
I have to say, I love the phrase from the gomega docs `On OS X the Ω character should be easy to type, it is usually just option-z: ⌥z` - that, to me, really says `it is a non-standard char, and you probably shouldn't do it`.
It it doesn't appear on my 101 key UK or US keyboard then I don't think it belongs in the code.
If I have to, I'll go do the sed change and submit a PR to change them all...

**Comment by devimc** [comment]
go for it, but then you have to change ```Should``` and ```ShouldNot``` with ```To``` or ```NotTo``` or ```ToNot``` to make it clear
