### ISSUE TITLE
docs: describe which tools we vendor with

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/tests#200]
We should document how we golang vendor (which tools etc.), to help other devs contribute to this repo.
I suspect the best place is actually the CONTRIB file.

**Comment by sboeuf** [comment]
Use github.com/golang/dep commit 24c37f5f336ec108d44e88a6f36125ab93c79951

**Comment by grahamwhaley** [comment]
Thanks @sboeuf Any background on exactly why that commit. OK, sure, i see that `dep` does not exactly have a nice rolling semver release history. My guess is we pinned to a commit that was the HEAD when we started using it. np there, just want some clarification so I can note why that commit in the docs.

**Comment by grahamwhaley** [comment]
This was fixed with https://github.com/kata-containers/community/pull/15
Closing
