### ISSUE TITLE
Need to be able to build and install Clear Containers from source 

### ISSUE THREAD

**Issue by egernst** [clearcontainers/tests#22]
If a user pulls down cc-oci-runtime and does a make install, Clear Containers will not work. It is assumed that binary artifacts area already installed.

We need to create an option to build all of the relevant parts for Clear Containers from source. This build will initially take a long time, but without this usability for Clear Containers is very poor. We need to allow developers to be able to rebuild a given release in its entirety from source, including things like the kernel and container image.

This will solve problems like: https://github.com/01org/cc-oci-runtime/issues/769

**Comment by egernst** [comment]
@sboeuf  @sameo  @mcastelino

**Comment by sboeuf** [comment]
The first step is to have scripts like the one related to Ubuntu setup here: https://github.com/clearcontainers/tests/pull/21
And as we discussed on IRC, the second step would be to add a way to build everything from scratch (kernel and images). I would suggest to add generic scripts doing this here. That way, any project (2.1 or 3.0) will be able to `go get` this repo and build everything it needs.
