### ISSUE TITLE
crio setup scripts are broken in semahpore ci.

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/tests#250]
https://github.com/kubernetes-incubator/cri-o/pull/687 added a new  dependency `libostree-dev` . We need to add it to ubuntu setup to build cri-o

*Debian, Ubuntu, and related distributions will also need a copy of the development libraries for ostree, either in the form of the libostree-dev package from the flatpak PPA, or built from source (more on that here).*

**Comment by sboeuf** [comment]
I will fix this issue
