### ISSUE TITLE
make check fails randomly when running CRI-O without any error messages

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#257]
SemaphoreCI suddenly terminates the `make check` when `CRI-O` is running.
The console does not show any errors and has been impacting some PRs since late last week. 

From https://semaphoreci.com/clearcontainers/tests/branches/pull-request-245/builds/6 
```
++ time bats --tap crio.bats
1..14
ok 1 ctr not found correct error message
ok 2 ctr termination reason Completed
ok 3 ctr termination reason Error
ok 4 ctr remove
ok 5 ctr lifecycle
ok 6 ctr logging
ok 7 ctr list filtering

```

From https://semaphoreci.com/clearcontainers/tests/branches/pull-request-255/builds/1
```
++ time bats --tap crio.bats
1..14
ok 1 ctr not found correct error message
ok 2 ctr termination reason Completed
ok 3 ctr termination reason Error
ok 4 ctr remove
ok 5 ctr lifecycle
ok 6 ctr logging
```

Sometimes the job fails on Test number 6 and sometimes in number 7.

**Comment by chavafg** [comment]
Still having issues like this one, but now on Test 8, now it seems that it started to happen more frequently: 



https://semaphoreci.com/clearcontainers/tests/branches/pull-request-299/builds/2
https://semaphoreci.com/clearcontainers/tests/branches/pull-request-295/builds/4
https://semaphoreci.com/clearcontainers/tests/branches/master/builds/132

**Comment by sboeuf** [comment]
CRI-O tests often hang on test 8 or 9. That's a known issue that should be solved by https://github.com/containers/virtcontainers/pull/333 and https://github.com/clearcontainers/proxy/pull/98.
For now, just retrigger the build.

**Comment by egernst** [comment]
@sboeuf @chavafg  - those PRs have been merged.  Is this issue resolved now?

**Comment by chavafg** [comment]
I haven't seen the error again. We can close this one.
