### ISSUE TITLE
Execute the top 100 images testing on every PR 

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#280]
We need to setup `localci` on a machine to test the top 100 images from docker.  
This may be executed apart from the functional and integration tests.

**Comment by grahamwhaley** [comment]
Did we deem this was actually practical?
Can we drop a few notes here about time and size of what this takes, for instance:
- how long does it take to download all those images
- how big is the complete set of images
- how long does it take to run all the tests (if all the images are already downloaded)

I think it is a worthy goal, but I think an easier immediate goal might be to run this complete test on every release candidate and release (before release ;-) ).

**Comment by egernst** [comment]
@chavafg @devimc  -- this is done now, right?

**Comment by chavafg** [comment]
Yes, this is already implemented, closing this issue.
