### ISSUE TITLE
Define qemu build options *once*

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/tests#339]
Currently, we have the qemu build (well `configure`) options scattered around the place:

- https://github.com/clearlinux-pkgs/qemu-lite/blob/master/configure
- https://github.com/clearcontainers/tests/blob/master/.ci/setup_env_ubuntu.sh
- https://github.com/clearcontainers/packaging/blob/master/qemu-lite/qemu-lite.spec
- https://github.com/clearcontainers/packaging/blob/master/qemu-lite/debian.rules

... and we're about to add:

- https://github.com/clearcontainers/packaging/blob/master/qemu-cc/qemu-cc.spec
- https://github.com/clearcontainers/packaging/blob/master/qemu-cc/debian.rules

This is not only confusing, it's potentially dangerous given some of the options relate to security.
There isn't much we can do about the clear linux build as that is a separate project, but for the remainder we need to define a *single* location these configure options live in.

## Proposal

1. Create https://github.com/clearcontainers/tests/tree/master/scripts/configure-hypervisor.sh
1. Add each option on a separate line.
1. Each option *must* have a comment explaining why it is being used.
1. Make all repos and scripts that need to build `qemu`/`qemu-lite`/`qemu-cc/`qemu-blah` run the script to determine the correct build options and thus guarantee the various builds are consistent.

Notes:

- this will be a change to the CI build which should mirror exactly how the packaged versions of `qemu*` are built.
- some consumers of the script will probably have to do a bit of work to import the output of this script (maybe by renaming config files to `file.in` and adding a `@HYPERVISOR_BUILD_OPTIONS@` or similar into `file.in`).

**Comment by jodh-intel** [comment]
This is going to be a multi-stage effort, but I'll start writing up a proper version of `qemu-configure.options.sh`...

**Comment by devimc** [comment]
I agree we have to keep all configure options in just one file (script) 
easy to maintain

**Comment by jodh-intel** [comment]
Replaced by https://github.com/clearcontainers/packaging/issues/44.
