### ISSUE TITLE
Improve CI scripts 

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#36]
There are now some issues in the CI scripts that we need to address: 

1. Some URLs are hard-coded and are used in more than 1 script. 
2. There are similar/duplicated scripts on other repos that are trying to do the same.

From @jodh-intel in #34: 

_Well, we now have 3 scripts that all hard-code the download URL. I'd still argue that install_cc_env_ubuntu.sh doesn't need to know that URL since it's querying for latest anyway.

Then, to avoid the last bit of duplication install_clear_image.sh and install_clear_kernel.sh could both source a script/config file for that URL. I know the URL is unlikely to change, but that isn't the point here.
https://github.com/01org/cc-oci-runtime/tree/master/.ci/ gets all this right and has been in use for a long time. But we now have these scripts plus the bunch in https://github.com/clearcontainers/runtime/tree/master/.ci all doing it slightly differently. It's getting rather confusing. Is the plan to migrate all the scripts from the runtime to the tests repo?_

**Comment by dlespiau** [comment]
Absolutely! we should migrate all testing scripts/code that are common to all repos to the `tests` repo. For instance testing the runtime should look like:

1. I assume the CI system will already have a checkout of the runtime PR. Compile and install the runtime
2. Run the runtime static checks and unit tests, grab coverage profile.
3. git clone git@github.com:clearcontainers/tests.git
4. install pause bundle, proxy and shim from scripts in the tests/ repo. This can either be from master branches or from special branches indicated by tags in the PR message (that features should be added later, not in the first version)
5. Run the functional tests. This includes grabbing coverage profiles for each run (or better, merging profiles with the unit-tests one after each test)
6. Run the docker integration tests
7. Run he CRI-O integration tests
8. Run he k8s tests
9. Publish aggregated coverage numbers (unit-tests + functional tests) in coveralls (See https://github.com/clearcontainers/runtime/issues/191)
10. Publish the HTML coverage on github pages

These are not set in stone just a guideline for discussion. Not everything has to exist in version one either. 

So, scripts that setup the environment and install the components should live in tests/. More generally, anything that is used by at least two repos should be in tests. Each repo will probably have a "master script" sequencing the first few operations, but it should be possible to share everything else (from step 5.).

There's a corresponding bug in the runtime at least https://github.com/clearcontainers/runtime/issues/178.
