### ISSUE TITLE
Make check problem with .ci/go-lint.sh

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/tests#41]
Currently as we have it now if I do a $ make check and if in my machine it is already installed the gometalinter it will produce the following errors

.ci/go-lint.sh
vendor/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable/colorable_windows.go:353::warning: cyclomatic complexity 89 of function (*Writer).Write() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:2304::warning: cyclomatic complexity 82 of function yaml_parser_scan_flow_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:665::warning: cyclomatic complexity 70 of function yaml_parser_fetch_next_token() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/readerc.go:91::warning: cyclomatic complexity 68 of function yaml_parser_update_buffer() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:2560::warning: cyclomatic complexity 53 of function yaml_parser_scan_plain_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/decode.go:331::warning: cyclomatic complexity 53 of function (*decoder).scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:2062::warning: cyclomatic complexity 52 of function yaml_parser_scan_block_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:1428::warning: cyclomatic complexity 50 of function yaml_emitter_write_double_quoted_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:983::warning: cyclomatic complexity 44 of function yaml_emitter_analyze_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:311::warning: cyclomatic complexity 37 of function yaml_emitter_emit_document_start() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/parserc.go:359::warning: cyclomatic complexity 33 of function yaml_parser_parse_node() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:1959::warning: cyclomatic complexity 30 of function yaml_parser_scan_tag_uri() is high (> 15) (gocyclo)
vendor/github.com/onsi/gomega/format/format.go:203::warning: cyclomatic complexity 29 of function formatValue() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:797::warning: cyclomatic complexity 29 of function yaml_emitter_select_scalar_style() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/resolve.go:86::warning: cyclomatic complexity 27 of function resolve() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/yaml.go:211::warning: cyclomatic complexity 26 of function getStructInfo() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:1132::warning: cyclomatic complexity 26 of function yaml_emitter_analyze_event() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/sorter.go:12::warning: cyclomatic complexity 26 of function (keyList).Less() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/parserc.go:93::warning: cyclomatic complexity 25 of function yaml_parser_state_machine() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/yamlh.go:438::warning: cyclomatic complexity 25 of function (yaml_parser_state_t).String() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:1369::warning: cyclomatic complexity 23 of function yaml_emitter_write_single_quoted_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/yamlh.go:143::warning: cyclomatic complexity 23 of function (yaml_token_type_t).String() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/encode.go:62::warning: cyclomatic complexity 22 of function (*encoder).marshal() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:1434::warning: cyclomatic complexity 22 of function yaml_parser_scan_to_next_token() is high (> 15) (gocyclo)
vendor/github.com/onsi/ginkgo/config/config.go:98::warning: cyclomatic complexity 22 of function BuildFlagArgs() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:1628::warning: cyclomatic complexity 21 of function yaml_emitter_write_folded_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:1312::warning: cyclomatic complexity 20 of function yaml_emitter_write_plain_scalar() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:211::warning: cyclomatic complexity 20 of function yaml_emitter_state_machine() is high (> 15) (gocyclo)
vendor/golang.org/x/sys/unix/creds_test.go:23::warning: cyclomatic complexity 20 of function TestSCMCredentials() is high (> 15) (gocyclo)
vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:98::warning: cyclomatic complexity 20 of function (*AsyncAssertion).match() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:1499::warning: cyclomatic complexity 19 of function yaml_parser_scan_directive() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:2250::warning: cyclomatic complexity 19 of function yaml_parser_scan_block_scalar_breaks() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/decode.go:509::warning: cyclomatic complexity 18 of function (*decoder).mapping() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/emitterc.go:504::warning: cyclomatic complexity 18 of function yaml_emitter_emit_flow_mapping_key() is high (> 15) (gocyclo)
vendor/github.com/onsi/gomega/matchers/support/goraph/bipartitegraph/bipartitegraphmatching.go:91::warning: cyclomatic complexity 18 of function (*BipartiteGraph).createSLAPGuideLayers() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:1713::warning: cyclomatic complexity 17 of function yaml_parser_scan_tag_directive_value() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:1771::warning: cyclomatic complexity 17 of function yaml_parser_scan_anchor() is high (> 15) (gocyclo)
vendor/github.com/onsi/ginkgo/reporters/stenographer/stenographer.go:442::warning: cyclomatic complexity 16 of function (*consoleStenographer).printSpecContext() is high (> 15) (gocyclo)
vendor/golang.org/x/sys/unix/syscall_unix_test.go:88::warning: cyclomatic complexity 16 of function TestPassFD() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/scannerc.go:1829::warning: cyclomatic complexity 16 of function yaml_parser_scan_tag() is high (> 15) (gocyclo)
vendor/gopkg.in/yaml.v2/yamlprivateh.go:63::warning: cyclomatic complexity 16 of function is_printable() is high (> 15) (gocyclo)
vendor/github.com/onsi/gomega/matchers/be_numerically_matcher.go:23::warning: cyclomatic complexity 16 of function (*BeNumericallyMatcher).Match() is high (> 15) (gocyclo)
WARNING: exec: "unconvert": executable file not found in $PATH
WARNING: exec: "unconvert": executable file not found in $PATH
WARNING: exec: "unconvert": executable file not found in $PATH
WARNING: exec: "goconst": executable file not found in $PATH
WARNING: exec: "goconst": executable file not found in $PATH
WARNING: exec: "goconst": executable file not found in $PATH
WARNING: exec: "staticcheck": executable file not found in $PATH
WARNING: exec: "staticcheck": executable file not found in $PATH
WARNING: exec: "staticcheck": executable file not found in $PATH
WARNING: exec: "interfacer": executable file not found in $PATH
WARNING: exec: "interfacer": executable file not found in $PATH
WARNING: exec: "varcheck": executable file not found in $PATH
WARNING: exec: "interfacer": executable file not found in $PATH
WARNING: exec: "structcheck": executable file not found in $PATH
WARNING: exec: "structcheck": executable file not found in $PATH
WARNING: exec: "varcheck": executable file not found in $PATH
WARNING: exec: "structcheck": executable file not found in $PATH
WARNING: exec: "varcheck": executable file not found in $PATH
WARNING: exec: "deadcode": executable file not found in $PATH
WARNING: exec: "deadcode": executable file not found in $PATH
WARNING: exec: "errcheck": executable file not found in $PATH
WARNING: exec: "deadcode": executable file not found in $PATH
WARNING: exec: "errcheck": executable file not found in $PATH
WARNING: exec: "errcheck": executable file not found in $PATH
WARNING: exec: "gosimple": executable file not found in $PATH
WARNING: exec: "gosimple": executable file not found in $PATH
WARNING: exec: "gosimple": executable file not found in $PATH
make: *** [check] Error 3

As those dependencies are not installed or found. This is fixed  by removing the gometalinter and running the $ make check
.ci/go-lint.sh
Installing:
  unparam
  aligncheck
  dupl
  gocyclo
  lll
  misspell
  deadcode
  gas
  ineffassign
  safesql
  staticcheck
  unused
  varcheck
  errcheck
  golint
  gosimple
  gotype
  unconvert
  goconst
  goimports
  interfacer
  structcheck

However, a change in the script it should be made that handles that situation.

**Comment by GabyCT** [comment]
@dlespiau ^

**Comment by GabyCT** [comment]
Also if you do a $ make check -f $GOPATH/src/github.com/clearcontainers/tests/Makefile there is a problem .
ci/go-lint.sh
make: .ci/go-lint.sh: Command not found
make: *** [check] Error 127

The $ make check runs correctly if you are only in the path
$ cd $GOPATH/src/github.com/clearcontainers/tests/
$ make check
.ci/go-lint.sh

**Comment by chavafg** [comment]
@GabyCT I think we can close this one as we will be using another approach (see #110) and `go-lint.sh` is  now removed with #153 .

**Comment by GabyCT** [comment]
@chavafg closing this now
