### ISSUE TITLE
`docker rm -f` hangs or leaves processes on multi-container remove

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/tests#492]
During testing/metrics tests I had a script that, after doing what it was meant to do. did a `docker rm -f` of all containers listed in `docker ps -qa` to clean up - and that sometimes hung. On further investigation it showed that sometimes it also left some of the runtime processes (shim and/or qemu and cc-runtime) around when it should not.

I put together a test over in #491 that can be used to show this.
My test system is a CC 3.0.0-beta1 OBS pacakage install on ubuntu server 16.04.2.

Running the test pretty much fails or hangs up for me at some point every time (with the default settings in the script - 110 nginx containers with 5 iterations). I use a 64Gb RAM machine btw, just for reference.
Sometimes it hangs up during the `rm -f` stage, and you just get stuck with a list of deleted containers on your screen. Normally if you then CTRL-C out of that, docker is hung up, and commands like `docker info` hang.

Sometimes the sanity checks will fire in the script, and then a `ps -ef` will normally show there are a bunch of qemu or other runtime components still running, but a `docker ps` and `docker ps -qa` will show that docker does not think there are any containers.

I'll put some system info below:

docker info:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: cc-runtime runc
Default Runtime: cc-runtime
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-92-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.31GiB
Name: bignuc
ID: ROOX:AUAH:KW7J:BADM:E3PW:ORDN:KL42:FKXQ:77LD:VGKO:ZFY4:OG64
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 509
 Goroutines: 365
 System Time: 2017-08-29T15:11:58.727574649+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

cc-runtime cc-env
```
[Meta]
  Version = "1.0.2"

[Runtime]
  [Runtime.Version]
    Semver = "3.0.0-beta.1"
    Commit = ""
    OCI = "1.0.0-rc5"
  [Runtime.Config]
    GlobalLogPath = ""
    [Runtime.Config.Location]
      Path = "/etc/clear-containers/configuration.toml"
      Resolved = "/etc/clear-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  [Hypervisor.Location]
    Path = "/usr/bin/qemu-lite-system-x86_64"
    Resolved = "/usr/bin/qemu-lite-system-x86_64"

[Image]
  Path = "/usr/share/clear-containers/clear-containers.img"
  Resolved = "/usr/share/clear-containers/clear-16910-containers.img"

[Kernel]
  Parameters = ""
  [Kernel.Location]
    Path = "/usr/share/clear-containers/vmlinuz.container"
    Resolved = "/usr/share/clear-containers/vmlinuz-4.9.35-62.container"

[Proxy]
  Type = "ccProxy"
  Version = "Version: 3.0.0-beta.1+"
  URL = "unix:///var/run/clear-containers/proxy.sock"

[Shim]
  Type = "ccShim"
  Version = "shim version: 3.0.0-alpha.4 (commit: 0)"
  [Shim.Location]
    Path = "/usr/libexec/clear-containers/cc-shim"
    Resolved = "/usr/libexec/clear-containers/cc-shim"

[Agent]
  Type = "hyperstart"
  Version = "<<unknown>>"
  [Agent.PauseBin]
    Path = "/var/lib/clear-containers/runtime/bundles/pause_bundle/bin/pause"
    Resolved = "/var/lib/clear-containers/runtime/bundles/pause_bundle/bin/pause"

[Host]
  Kernel = "4.4.0-92-generic"
  CCCapable = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz"
```

**Comment by grahamwhaley** [comment]
/cc @sboeuf @devimc @egernst @MarioCarrilloA  FYI. I'm not going to chase this down right now - I need to go fix up my original test for something else (by using a two stage `stop` and `rm` instead of `rm -f`. But, let me know if you need me to try something or dig up more info.
At one stage I did turn on logging, and I think that made the test pass :-(  I might have be in some 'transition' though - so that needs re-checking.

**Comment by devimc** [comment]
running the same test of https://github.com/clearcontainers/runtime/issues/570 but using a kernel with this patch, I don't see any instance of qemu running and all rootfs have been unmounted

```
$ ps -ef | grep qemu
fedora   31233  1356  0 09:34 pts/1    00:00:00 grep --color=auto qemu
```
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
```
$ mount  | grep "docker" 
/dev/mapper/fedora-root on /var/lib/docker/overlay type xfs (rw,relatime,attr2,inode64,noquota)
```

**Comment by grahamwhaley** [comment]
This has been fixed through a number of critical PRs, including at least:
https://github.com/containers/virtcontainers/pull/396
https://github.com/clearcontainers/proxy/pull/144

Closing.
