### ISSUE TITLE
Install components first, then test them.

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/tests#5]
PR https://github.com/clearcontainers/tests/pull/4 currently tests components in place (in their git repo):

```
# Path of Clear Containers Runtime
RUNTIME ?= "${GOPATH}/src/github.com/clearcontainers/runtime/cc-runtime"

# Path of Clear Containers Proxy
PROXY ?= "${GOPATH}/src/github.com/clearcontainers/proxy/cc-proxy"

# Path of Clear Containers Shim
SHIM ?= "${GOPATH}/src/github.com/clearcontainers/shim/cc-shim"
```

We should:

1. for each component: build and install (this could be system wide or in a separate prefix).
2. run the tests on installed components.

**Comment by chavafg** [comment]
Closing this issue as it was fixed with #45
