### ISSUE TITLE
metrics: Re-factorization/Categorization tests

### ISSUE THREAD

**Issue by MarioCarrilloA** [clearcontainers/tests#503]
Some metrics tests have minimal but relevant details such as:

- Some tests need a pair of things for supporting `runc` as runtime
- Mix different semantic in one test (then mix different tools).
- Save different kind of results in the same file
- Maybe, a pair of functions that could be joined in one
- Missing documentation.

Improving these points we can have a better categorization and at the same time more semantic in the current stuff.

/cc: @bwarden  @grahamwhaley @mcastelino @egernst

**Comment by grahamwhaley** [comment]
Hi @MarioCarrilloA @bwarden Whilst here, I was just utilising the `kill_processes_before_start`:
https://github.com/clearcontainers/tests/blob/master/metrics/lib/common.bash#L192
and although it stops any running containers with a `kill`, I think it would also make sense to then `rm` the ones it stopped. This will help get rid of any 'container name clashes' that @MarioCarrilloA has been seeing like on #524 - and, I could also then use this function as a 'cleanup' function at the end of a test as well (which we seem to be missing - maybe I should just do that in my test and remember which containers I've launched and clean up after myself...)
Thoughts? (although I know @MarioCarrilloA probably has a closely related PR about to land maybe??)
