### ISSUE TITLE
Store jenkins configuration in this repo

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/tests#540]
Maybe under `data/ci/jenkins/config/` or similar.

**Comment by jodh-intel** [comment]
This is relatively important to ensure we can recreate the jenkins CI environment quickly should the need arise.

**Comment by grahamwhaley** [comment]
I'll just make the obvious note, that we need to make sure we don't store any 'secret' stuff - like access keys etc. - but other than that, I have a feeling for Jenkins it may pretty much be a `cp -r` of a config subdir and xml or similar file.

**Comment by jodh-intel** [comment]
Agreed. @sboeuf - do you have any thoughts on how we can ensure the jenkins data can be kept up-to-date in this repo? Are all the sensitive elements kept in different files?

**Comment by sboeuf** [comment]
@jodh-intel @grahamwhaley I think that we basically need
```
/var/lib/jenkins/
            |----------> config.xml
            |----------> jobs/
                           |----------> job1/
                                         |----------> config.xml
                           |----------> job2/
                                         |----------> config.xml
```
The config.xml files have all the informations needed to replicate the Jenkins server configuration. About the secrets credentials, they don't contain directly the keys, they have some intermediate keys that are interpreted in thanks to the `secrets/` folder, but we don't want to share this one.

Basically, this would mean that if we wanted to duplicate a similar setup, we need another server with Jenkins installed, and we would replace the config.xml files. I think it should work pretty well, but we will maybe have some issues since the credentials won't be found in the `secrets/` folder. And also, I am wondering how the plugins are gonna fit with this. I think we need to list the plugins that we need and their version. Maybe a solution could be to copy all the plugins (`plugins/` directory) to make sure we won't have compatibility issues.

**Comment by sboeuf** [comment]
@jodh-intel About the way to update, I agree with @grahamwhaley that copying latest version of those `config.xml` sounds the best thing to do.

**Comment by jodh-intel** [comment]
@sboeuf - ack. Since the secret stuff is kept in a different area, I was wondering if we could "gitify" `/var/lib/jenkins/`. Whatever we do, it would also be potentially useful to have a cron job that diffs the `config.xml` files in `/var/lib/jenkins/` against those stored here and warns a handful of the team to ensure we don't forget to either pull or push ;)

**Comment by sboeuf** [comment]
@jodh-intel I don't think we can/need to gitify since we are gonna be able to see the differences everytime we update the repo where we keep the last good config.

**Comment by jodh-intel** [comment]
Sure, but if we use a git repo actually on the jenkins systems, that might help avoid us avoid updating the config in this repo (if the jenkins config file call scripts, the first thing those scripts could do is a `git pull` and a check to see if there are any uncommitted local changes).

**Comment by jodh-intel** [comment]
To be crystal clear, all I am proposing is that we put as much of our Jenkins configuration in a git repository that lives under https://github.com/clearcontainers/ "somewhere" and that if at all possible we have a clone of that repository on the Jenkins systems so we avoid having to manually "sync" files between the git repo on github and the files living on the Jenkins systems.

@grahamwhaley's comment https://github.com/clearcontainers/tests/pull/545#discussion_r139655908 pretty much summarises it.

**Comment by grahamwhaley** [comment]
OK, I think there are three items/phases here...
1) get the Jenkins configs backed up into a repo - #545 is handling that. Placing it where it is right now in that PR is fine as a start
2) Decide if we want to put that data in a repo of its own so we can then completely manage (or sync/backup easier) the jenkins configs directly through git. I think jenkins will ignore the .git subdir it gains, so it should probably work. If we do this, then making a separate repo (clearcontainers/jenkins or similar) would be much cleaner than trying to bury a repo-in-a-repo. I know we don't want repo explosion, but this is a good case.
3) Then mid-term we should see if we can extract as much script stuff out of the jenkins files (gui) and into say tests/.ci/* so we get the Jenkins GUI out of our workflow, and manage the majority of Jenkins changes through our normal workflow of files under the clearcontainers/tests repo (and clearcontainers/jenkins repo if that is appropriate).

For (1) - if we can answer the queries on #545, then I think we can land that
For (2) - I vote for a new repo (and, yes, that will supersede (1) - and we can skip (1) and go straight to (2) if we want)
For (3) - we can delay that a little and work on it piecemeal - if we agree that is the future/plan then I can open an Issue detailing it more

**Comment by sboeuf** [comment]
@grahamwhaley Thanks for summarizing, this is much clearer. IMO, we should go straight with (2) because this sounds like the best thing to do.

**Comment by grahamwhaley** [comment]
@sboeuf np. if we get an ack from @sameo , then we (I can I think - not sure who else can apart from @sameo and @mcastelino - maybe @sboeuf has elevated powers still....) create https://github.com/clearcontainers/jenkins repo, and we can work on (2).

**Comment by grahamwhaley** [comment]
@sboeuf - try https://github.com/clearcontainers/jenkins - enjoy!

**Comment by sboeuf** [comment]
@grahamwhaley Thanks :)

**Comment by grahamwhaley** [comment]
If you have issues accessing that repo, then it might be because of:
https://github.com/clearcontainers/jenkins/issues/1
(might need to add teams and members to the repo to get perms set up)

**Comment by sboeuf** [comment]
Can be closed since it's gonna tracked by https://github.com/clearcontainers/jenkins/issues/2

**Comment by jodh-intel** [comment]
Agreed - closing.
