### ISSUE TITLE
Simplify CI setup (drop Travis and Semaphore and switch to Jenkins)

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/tests#541]
At some point, we need to consider switching fully to Jenkins.

Task list:

- [x] Fix #540.
- [x] **Enable unit-tests under Jenkins (currently, they only run under Travis)**.
- [x] Enable coveralls.io under Jenkins (currently triggered by Travis [2]).
- [x] Remove Travis badge from [1].
- [x] Remove Semaphore badge from  [1].
- [x] Add a jenkins badge to [1].
- [x] Ensure [checkcommits](https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits) runs under Jenkins.
- [x] Migrate slack config from `.travis.yml`.

---
[1] - https://github.com/clearcontainers/runtime/blob/master/README.md
[2] - https://github.com/clearcontainers/runtime/blob/master/.travis.yml#L21.L22

**Comment by jodh-intel** [comment]
Hi @sboeuf - We don't need to wait until we disable the other CI's to enable the unit-tests under Jenkins, so would be great to get that up-and-running (maybe as part of #540?)

**Comment by sameo** [comment]
We just removed the semaphore CI webhooks from the agent, shim, proxy, runtime and tests repos.

**Comment by sboeuf** [comment]
No need to migrate slack from the .travis.yml since I had added (few weeks ago) some slack webhooks for every repo. Those webhooks are triggered by the main events such as a pull request, a comment, a new issue, ....

**Comment by sboeuf** [comment]
I think this can be closed since all boxes have been ticked. WDYT @jodh-intel ?

**Comment by jodh-intel** [comment]
Agreed - closing.

(related: https://github.com/clearcontainers/jenkins/pull/3).
