### ISSUE TITLE
Add ability to rebuild a jenkins build

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/tests#556]
Travis and Semaphore both offer the ability to rebuild a build. This feature doesn't appear to be part of the default Jenkins setup so it looks like we need something like:

- https://wiki.jenkins.io/display/JENKINS/Rebuild+Plugin
  (https://github.com/jenkinsci/rebuild-plugin)

**Comment by grahamwhaley** [comment]
+1 for that - particularly useful when we are trying to track down those flaky items etc.

**Comment by sboeuf** [comment]
I have installed the `Rebuilder` plugin. It now allows us to go to a specific build and rebuild it manually by pressing the Rebuild button !
