### ISSUE TITLE
CI: add console parser plugin to Jenkins systems

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/tests#557]
The console output is currently a little hard to read sometimes (it has just gotten better with a UI skin change - but we still get a bunch of special formatting chars turning up, and finding error lines is tricky in the large logs).
It might be an idea to investigate some of the Jenkins console parsing plugins so we can get some auto-highlighting of errors and warnings in the logs. From a quick surf, something like:
https://wiki.jenkins.io/display/JENKINS/Log+Parser+Plugin
https://wiki.jenkins.io/display/JENKINS/Console+Parser+Plugin

**Comment by sboeuf** [comment]
@grahamwhaley I have added the ANSI color plugin which allows to interpret the special characters in the console output. Those characters were referring to specific format and colors. For example, look at those console outputs here http://cc-jenkins-ci.westus2.cloudapp.azure.com/job/clear-containers-shim-azure-ubuntu-17-04/9/console and let me know if you consider this is enough to close this ticket.
I think we should close it but it's up to you ;)

**Comment by jodh-intel** [comment]
@grahamwhaley - is this good to close, or shall I migrate it to a new issue in the jenkins repo?

**Comment by grahamwhaley** [comment]
let me go review - I have not noticed a difference, but it might be that the plugin is so good that now my brain doesn't twitch....

**Comment by grahamwhaley** [comment]
I think we can close this. The ANSI plugin helps a lot by interpreting the colour codes, and that  cleans up the output a lot. The other plugins may (have) let us define our own set of keywords to highlight like 'error, fail, failure, timeout' etc. - but I suspect they would actually need some tuning, and would really need regexp capability to filter our logs well (quite a lot of those words appear as arguments to commands in the verbose output for instance).
If we find we need to make further improvements in the future then we can re-open this or make a new Issue.
