### ISSUE TITLE
CI: Add pipeline Jenkins plugin

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/tests#558]
This Jenkins plugin will allow us to get a breakdown of where the build time is being spent:

- https://wiki.jenkins.io/display/JENKINS/Pipeline+Stage+View+Plugin

**Comment by grahamwhaley** [comment]
Ooh :-) That will at least be helpful during this startup and optimise (deploy) phase...

**Comment by jodh-intel** [comment]
Well, it looks like we can create individual stages for arbitrary commands meaning we can make it as granular as we want ;)

**Comment by jodh-intel** [comment]
Closing - replaced by https://github.com/clearcontainers/jenkins/issues/7.
