### ISSUE TITLE
metrics: emailreport: is not vendored

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/tests#572]
The email report tool is not 'vendored':
https://github.com/clearcontainers/tests/tree/master/cmd/emailreport

which means it can fail to build when running automation such as:
https://github.com/clearcontainers/tests/blob/master/.ci/run_metrics_ci.sh#L30
when the package dependencies are not installed already on the system.

Some details of our vendoring method/tools can be found on the pending Issue at:
https://github.com/clearcontainers/runtime/issues/332

Any issues, shout here and we will try to help.
/cc @sboeuf

**Comment by jodh-intel** [comment]
Worth pointing out that `emailreport` also lacks a `--version` flag and/or version print at runtime which could be useful for debugging.

Looks like `fetchbranches`, `checkmetrics` are also missing version details.

**Comment by MarioCarrilloA** [comment]
Hi @jodh-intel , good point I will add another issue for missing `--version` flag
