### ISSUE TITLE
docker and CRI-O integration tests under runtime repo should be migrated to this repo

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#59]
Currently, there are some docker integration tests in the clearcontainers/runtime repository. 

Those tests should be migrated here.

**Comment by chavafg** [comment]
Also CRI-O tests should be moved here.

**Comment by egernst** [comment]
@chavafg -- this is stale -- should this be closed now?

**Comment by chavafg** [comment]
Yes, closing this issue. The CRI-O tests are already here.
