### ISSUE TITLE
swarm.bats should explicitly test the nginx service

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/tests#629]
The [swarm integration test](https://github.com/clearcontainers/tests/blob/master/integration/swarm/swarm.bats) needs to explicitly test that it can get a response from `nginx` to ensure the runtime has setup the networking correctly.

I think all that needs to be done is for a new `@test` to be added that does the following for each replica:

```
$ timeout=10
$ curl --connect-timeout $timeout 127.0.0.1:8080/hostname
```

Does this sound right @GabyCT , @mcastelino?

**Comment by mcastelino** [comment]
@jodh-intel @GabyCT yes we should add this for sure. I thought we were at least testing the DNS resolution for nginx in swarm.

**Comment by mcastelino** [comment]
@GabyCT we do test this as part of the k8s ci. So we should do the same here.

https://github.com/clearcontainers/tests/blob/master/integration/kubernetes/nginx.bats#L43

**Comment by jodh-intel** [comment]
Hi @GabyCT - could you look at this today?

**Comment by GabyCT** [comment]
@jodh-intel , this is working with me

$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                  PORTS               NAMES
23b521637ce3        mcastelino/nginx:latest   "/bin/bash -c 'hostna"   2 seconds ago       Up Less than a second   80/tcp, 443/tcp     testswarm.1.c2y13xqhy97wbxldormay2uw2

$ unset http_proxy

$ curl http://127.0.0.1:8080/hostname
23b521637ce3

@jodh-intel you need to do an unset http_proxy before and I tested it with the following configuration
cc-runtime  : 3.0.4
commit   : 28bd75d
OCI specs: 1.0.0-rc5
Docker version 1.12.1, build 23cf638

I will add the test to swarm.bats

**Comment by jodh-intel** [comment]
I don't have any proxies set, but it still hangs for me. I'm using:

```
cc-runtime  : 3.0.4
   commit   : 39b11f8d84cc7d2139e8a98c19c5a23df2593a28
   OCI specs: 1.0.0-dev
docker: 17.05.0-ce
```

However, if it's working for you, please can you make the change to `swarm.bats` on this issue so we can ensure that new PRs get tested using `curl`.

**Comment by jodh-intel** [comment]
The bats test should also check to ensure the version of docker matches `docker_swarm_version=` in the runtimes `versions.txt` if possible [*] (see https://github.com/clearcontainers/runtime/pull/782).

---

[*] - the complications are checking the version of docker installed (might need to do a `grep ^$docker_swarm_version` on the output of `dpkg -l` / `rpm -qa`). But also, what if the `tests` repo isn't testing the `runtime` repo?
