### ISSUE TITLE
Integration test dont use CC_RUNTIME makefile variable

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/tests#637]
Functional tests uses CC_RUNTIME to know what runtime use. But integration test dont so if you run:

`make integration`

Will rely on the guess the cc-runtime is the default runtime in docker and was registered with as `cc-rumtime`

**Comment by grahamwhaley** [comment]
Just to note, I believe the metrics currently use `RUNTIME` - we should probably define and unify this across all the tests at some point :-)

**Comment by jcvenegas** [comment]
`RUNTIME` make more sense to me. It  should be possible to use any runtime. @chavafg do you know CC_RUNITME is being used as part of the validation somewhere ? 

A quick grep under clearcontainers repositories show that is used only here:
```
tests/Makefile:CC_RUNTIME ?= cc-runtime
tests/Makefile: RUNTIME=${CC_RUNTIME} ./test/test_runner.sh crio.bats
tests/Makefile: ./ginkgo -v functional/ -- -runtime ${CC_RUNTIME} -timeout ${TIMEOUT}
tests/Makefile: RUNTIME=${CC_RUNTIME} ./metrics/run_all_metrics.sh
tests/Makefile: ./ginkgo -v -focus "${FOCUS}" ./integration/docker/ -- -runtime=${CC_RUNTIME} -timeout ${TIMEOUT}
tests/.git/COMMIT_EDITMSG:Use CC_RUNTIME variable from Makefile instead of expect

```

**Comment by chavafg** [comment]
@jcvenegas yes, that Makefile must be the only place where we use it.

**Comment by jcvenegas** [comment]
@chavafg @grahamwhaley  ok, changed the name .
