### ISSUE TITLE
check why swarm replicas failed randomly

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/tests#694]
check why the swarm.bats test is failing randomly

**Comment by chavafg** [comment]
Thanks for opening this issue @GabyCT. 

Some logs from Jenkins:

```
not ok 4 check mtu values in different interfaces
# (in test file integration/swarm/swarm.bats, line 100)
#   `[ "$mtu_value_eth0" = "$mtu_value_tap0" ]' failed
# Swarm initialized: current node (ecncxlgj6lra727qykus0r9y6) is now a manager.
# 
# To add a worker to this swarm, run the following command:
# 
#     docker swarm join --token SWMTKN-1-344w4asinwwknzv7q6qu8l6oozajrqvhf5yyghfokeg6vr28xq-b8h5dqf0678w85jboco95moaq 10.0.0.5:2377
# 
# To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
# 
# okl2bbjfdytwdvq49y3nt4nkw
# Since --detach=false was not specified, tasks will be created in the background.
# In a future release, --detach=false will become the default.
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# ID                  NAME                MODE                REPLICAS            IMAGE                 PORTS
# okl2bbjfdytw        testswarm           replicated          0/4                 gabyct/nginx:latest   *:8080->80/tcp
# testswarm
# Node left the swarm.
Makefile:49: recipe for target 'swarm' failed
make: *** [swarm] Error 1
Build step 'Execute shell' marked build as failure
```

**Comment by chavafg** [comment]
I tried to reproduce locally but couldn't, but on Azure machines I could see it when running the swarm tests on a loop.

**Comment by chavafg** [comment]
reopening this issue until we really fix it.

**Comment by GabyCT** [comment]
The main issue is that the service ip address is missing. 
1. Inspect the service in order to retrieve the service ip with
$ docker service inspect "${service_name}"
"VirtualIPs": [
                {
                    "Addr": "10.255.0.3/16"
                }
2. However, when you do inspect the interface in the replica the value of "10.255.0.3" is missing at the eth0 interface
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc mq state UP group default qlen 1000
    link/ether 02:42:0a:ff:00:04 brd ff:ff:ff:ff:ff:ff
    inet 10.255.0.4/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:feff:4/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.3/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:3/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0

Here are the setup configurations that I am using:
cc-runtime  : 3.0.7
commit   : c279167f96d9eec3b1ef3d705da3cb44bb3d3450
OCI specs: 1.0.0-dev
Docker version 17.09.0-ce, build afdb6d4

**Comment by GabyCT** [comment]
opened issue https://github.com/clearcontainers/runtime/issues/809
