### ISSUE TITLE
metrics: network: update iperf3 version in container

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/tests#765]
We use `iperf3` for a number of networking tests, from container `gabyct/networking`.
We previously worked around a 9p unlink issue using a tmpfs mount:
https://github.com/clearcontainers/tests/blob/master/metrics/network/network-metrics-iperf3.sh#L62
but with new agent functionality that restricts the root system capability in a container (to make us more equivalent to a real un-priv container), that mount is no longer allowed.
The key issue iperf3 runs into is trying to open and unlink a tmpfile. One possible workaround is to set the TMPDIR so that the tmpfile does not live on the 9pfs, but in a ramfs (similarly to how the mount fix was working).
This should work, as `iperf3` now has the code to check and use the TMP vars:
https://github.com/esnet/iperf/blob/eddfb8267e196f9f96cd80b5e99238f9ffe48f97/src/iperf_api.c#L3169
but, it looks like this merged in iperf3 version 3.2 or thereabouts (this PR https://github.com/esnet/iperf/pull/517 around March/April 2017) - but we currently have iperf 3.0.11 inside the `gabyct/networking` container.

@GabyCT - could you update your container with a more recent `iperf3` ?

**Comment by grahamwhaley** [comment]
/cc @mcastelino - yes, we should be able to work around the iperf3 9p issue with TMPDIR, once we update the version of iperf3 we have in the test container.
Hmm, looks like iperf3 v3.0.11 is the latest on Ubuntu 16.04.

**Comment by grahamwhaley** [comment]
To note - another option would be to enable support for `--tmpfs` or `--mount type=tmpfs` in the agent - that is, honor the tmpfs `Mount` items passed through to the runtime - that is probably slightly more work though (but, maybe not that much..)

**Comment by GabyCT** [comment]
@grahamwhaley I will update the iperf3 in the docker hub image

**Comment by GabyCT** [comment]
@grahamwhaley this has been updated, the image has now the latest iperf3
iperf3 --version
iperf 3.3 (cJSON 1.5.2)
