### ISSUE TITLE
Add test to check a container process cannot gain additional privileges when no-new-privileges flag is passed on the docker command line. 

### ISSUE THREAD

**Issue by amshinde** [clearcontainers/tests#811]
Related changes that need to land:
https://github.com/containers/virtcontainers/pull/529
https://github.com/clearcontainers/agent/pull/186

The test would include starting a container as a non-root user, and then on run a setuid program. The process would not be able to gain root privileges. 
Please refer to this blog that details this:
https://www.projectatomic.io/blog/2016/03/no-new-privs-docker/

**Comment by GabyCT** [comment]
@amshinde following the example of https://www.projectatomic.io/blog/2016/03/no-new-privs-docker/

I did the following
$ docker run -it --rm --user=1000 gabyct/cc-test-privileges
Effective uid: 0

$ docker run -it --rm --user=1000 --security-opt=no-new-privileges gabyct/cc-test-privileges
Effective uid: 0

$ docker run -it --runtime runc --rm --user=1000 gabyct/cc-test-privileges
Effective uid: 0

$ docker run -it --runtime runc --rm --user=1000 --security-opt=no-new-privileges gabyct/cc-test-privileges
Effective uid: 1000

We can see that with runc the effective uids are different as we expect but with cc-runtime they are the same. I see that the changes are merged, is something else missing?

I am using the following configuration
cc-runtime  : 3.0.12
commit   : 9014fe377ba9db875e08b28a801164febad43264
Docker version 1.12.1, build 23cf638
runc version 1.0.0-rc4+dev

**Comment by GabyCT** [comment]
@amshinde, I followed the instructions from https://www.projectatomic.io/blog/2016/03/no-new-privs-docker/ and the test is already here https://github.com/clearcontainers/tests/pull/836
