### ISSUE TITLE
Add test to verify capabilities can be added and dropped with docker run command.

### ISSUE THREAD

**Issue by amshinde** [clearcontainers/tests#818]
Refer to this issue created in the agent repo:
https://github.com/clearcontainers/agent/issues/181

Capabilities can be added/removed with  --cap-add or --cap-drop with Docker.
Once support for capabilities has landed, we need to create and enable a test for this. 
(https://github.com/containers/virtcontainers/pull/542)

**Comment by amshinde** [comment]
cc @GabyCT

**Comment by amshinde** [comment]
Capabilities can also be added with docker exec. The runtime needs to be modified to support this.
I have created a separate issue for the exec case : https://github.com/clearcontainers/tests/issues/819

**Comment by GabyCT** [comment]
@amshinde  we have already a test with this for the case of `docker run`
https://github.com/clearcontainers/tests/blob/master/integration/docker/cap_test.go

**Comment by GabyCT** [comment]
@amshinde , I reviewed `docker exec` and the option to add or drop capabilities is not part of the command.

**Comment by jodh-intel** [comment]
I'm not seeing it for `docker exec` either. What version of `docker` are you using @amshinde? Or are you referring to `runc exec --cap` maybe?

**Comment by amshinde** [comment]
@jodh-intel @GabyCT My bad, I saw runc support capabilities for exec, I assumed that it was a docker option.
