### ISSUE TITLE
Jenkins setup breaks checkcommits

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/tests#876]
`.ci/jenkins_job_build.sh` is breaking `checkcommits` by not creating a separate branch for the PR under Jenkins.

See: https://github.com/clearcontainers/jenkins/issues/40.

**Comment by grahamwhaley** [comment]
So, I understand what you are saying @jodh-intel , and it sounds plausible - but, has `checkcommits` not been picking up issues - in which case, it feels like there is something I'm missing here. Is this true for all of our repos? Hmm, or maybe it's only been picking up issues on Travis, and not Jenkins?

**Comment by jodh-intel** [comment]
The problem is specific to our Jenkins setup, hence all CC repos I think

Kata is fine as it's using Travis which has a pretty sane `git` env (which `checkcommits` detects):

- https://github.com/clearcontainers/tests/blob/master/cmd/checkcommits/checkcommits.go#L453..L459

**Comment by jodh-intel** [comment]
Basically, `checkcommits` requires the PR branch to `!=` the `master` branch. Or if it does, it needs a way to find the `HEAD` commit of `master` (locally).

The question is, if we change the Jenkins config as I've suggested on https://github.com/clearcontainers/jenkins/issues/40, will something else break I wonder? I can raise a test PR, but I'd like to get feedback from @sboeuf and @chavafg too.

**Comment by chavafg** [comment]
So this line is the guilty one: https://github.com/clearcontainers/tests/blob/master/.ci/jenkins_job_build.sh#L57 
but seems like it was done this way to make coveralls work (as the commit message suggests). @sboeuf do you know if changing it would brake coveralls?

**Comment by jodh-intel** [comment]
@chavafg, @sboeuf - if that's the case, we could always create PR branch, run checkcommits, then merge the PR branch into master before coveralls is run?

**Comment by sboeuf** [comment]
@chavafg @jodh-intel I am not sure about the details here for checkcommits, but please be very careful with this line since this is in charge of the whole sanity of the test. You gotta be careful that we don't end up testing the wrong version or even master in case we actually want to test a PR.

**Comment by jodh-intel** [comment]
Unless someone takes a look today, I'll have a go at doing https://github.com/clearcontainers/tests/issues/876#issuecomment-362014226 tomorrow and see if I can avoid breaking the world.... ;)

**Comment by sboeuf** [comment]
@jodh-intel I don't have time to take a look today, but please let me know tomorrow how your investigations went.
