### ISSUE TITLE
Implement localCI pnp metrics failure reporting tool

### ISSUE THREAD

**Issue by MarioCarrilloA** [clearcontainers/tests#89]
Inputs:
- PnP tests results

Outputs:
- Report as a table
- Ship log files of PnP tests

**Comment by grahamwhaley** [comment]
Also:
 send report out as an email.
 Allow 'whitelist checking' to only send reports to members of the relevant 'github org'
 Allow addition of a 'CC' list for the emails as well.

we'll need a config file. I can forsee it will need to have at least:
 - the SMTP server address to send, and/or an email program to invoke
 - The CC list
 - possibly the program to invoke to get the report table data
 - possibly the program/command to invoke to get the log data

and then I think there will be command line options:
 - enable/disable whitelisting

Something I've not quite decided on is how the program knows which PR/commit it is processing - is that something localCI passes in or sets in the environment, or do we just presume it is the current git HEAD for instance, and extract info from the git refs etc. if we need to. @devimc do you have any thoughts here?

**Comment by devimc** [comment]
@grahamwhaley if you need an environment variable I can added it
