### ISSUE TITLE
ci: does not install ksm-throttler, like packaging does

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/tests#913]
When we switched from a single proxy to multi-proxy, we moved the KSM handling from the proxy to the https://github.com/kata-containers/ksm-throttler, and added it to the packaging https://github.com/clearcontainers/packaging/tree/master/ksm-throttler

What it appears we did not do was update the .ci install scripts https://github.com/clearcontainers/tests/blob/master/.ci/install_proxy.sh to both stop installing the proxy service files, and to install and start (if necessary) the ksm-throttler.

Related to #910 #911 https://github.com/clearcontainers/proxy/pull/177

**Comment by jodh-intel** [comment]
https://github.com/clearcontainers/proxy/pull/177 does indeed seem to have fallen off the stack :smile:.

I'll pick that up again, but yes, the tests shouldn't be relying on any KSM functionality from the proxy since when the PR above lands... it's gone.

**Comment by chavafg** [comment]
@grahamwhaley, @jodh-intel 

I'll work on this, but let me know if this approach would be correct.

1. Create `.ci/install_ksm_throttler.sh` to install the `ksm-throttler` using `go get github.com/kata-containers/ksm-throttler && make && sudo make install`
2. If system is running metricsCI, then we do not start `vc-throttler.service`, else, we start the service. 
3. Check if `cc-proxy` service file exists. If it exists, then we continue setting flag `-ksm initial`. If it does not exists (when https://github.com/clearcontainers/proxy/pull/177 lands), then we do not fail.

After the Proxy change lands, we can again remove the code that checks and modifies the service file.

Is this ok, or am I missing something?

**Comment by jodh-intel** [comment]
Hi @chavafg - steps (1) and (2) look fine, but I'd be tempted to make (3) even simpler since once we're using `ksm-throttler`, we should just ignore any `cc-proxy` service details entirely:

```
sudo systemctl stop cc-proxy || true
sudo systemctl disable cc-proxy || true
```
