### ISSUE TITLE
improve and/or document the way we run CRI-O tests

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/tests#921]
We currently run a subset of the CRI-O tests from `github.com/kubernetes-incubator/cri-o/tests`, but there is no documentation of what approach we follow. We also need to find a way to have a more reliable process, since our tests can be outdated at some point.

For reference, this was a previous discussion:
https://github.com/clearcontainers/tests/pull/919#pullrequestreview-97518645

**Comment by GabyCT** [comment]
The approach that we will take is that after cloning the `github.com/kubernetes-incubator/crio-o/tests`, we will run the CTR tests. However, currently only 16 of the 30 are passing so the rest of them will have a skip.
