### ISSUE TITLE
Testing Disk IO Performance

### ISSUE THREAD

**Issue by chandrabvv** [clearcontainers/tests#972]
How can we turn off caching of disk in memory to test the disk IO performance? We can turn off caching In KVM virtual machine by setting the cache=none in config file of virtual machine, but i am not able to find such option in clear containers. In case of Docker containers, simply setting directio in the application will do the job but not in the case of clear container because it is a light weight VM and processes running inside it will not be visible to host kernel.

**Comment by devimc** [comment]
@chandrabvv  thanks for raising this issue, but Clear Containers is no more supported, please use Kata Containers instead https://github.com/kata-containers/
